name: client_flutter
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  web_socket_channel: ^2.4.0

  # Generators
  freezed_annotation: 2.2.0
  json_annotation: 4.8.1
  injectable: 2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.0
  build_runner: 2.4.5
  freezed: 2.3.5
  json_serializable: 6.7.0

flutter:
  uses-material-design: true
